---
- name: Deploy SSO Realm
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - sso_realm/defaults/main.yml

  tasks:
    - set_fact:
        resources_dir: "{{ resources_base_dir }}/sso_realm"
        work_dir_name: sso_realm
        
    - name: create work directory
      command: mktemp -d /tmp/{{ work_dir_name }}-XXXXXX
      register: mktemp
      changed_when: False

    - set_fact:
        work_dir: "{{ mktemp.stdout }}"

    - name: get domain url
      shell: echo $({{ openshift_cli }} get route console -o jsonpath='{.spec.host}' -n openshift-console | sed "s/console-openshift-console.//g")
      register: ocp_domain_host
      when: ACTION is not defined or ACTION == "install"

    - name: set ocp_domain fact
      set_fact: 
        ocp_domain: "{{ ocp_domain_host.stdout }}"
      when: ACTION is not defined or ACTION == "install" 

    - include: sso_realm/tasks/main.yml  